package store

import (
	"database/sql"

	"github.com/anxhukumar/hashdrop/server/internal/database"
)

// Store struct for carrying db queries generated by sqlc and the sql connection
type Store struct {
	Queries *database.Queries
	DB      *sql.DB
}

func NewStore(dbConn *sql.DB) *Store {
	return &Store{
		Queries: database.New(dbConn),
		DB:      dbConn,
	}
}
